version: 2
updates:
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"
    labels:
      - "type/build"
      - "scope/dockerfile"

  # Maintain Python dependencies (test suite)
  - package-ecosystem: "pip"
    directory: "/test/requirements"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci"
    labels:
      - "type/ci"
