version: '2.1'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    environment:
      - ENABLE_IPV6=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${NGINX_PROXY_PATH}/data/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_PROXY_PATH}/data/html:/usr/share/nginx/html
      - ${NGINX_PROXY_PATH}/data/certs:/etc/nginx/certs
    networks:
      - nginx-proxy

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    environment:
      # - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
      - DEFAULT_EMAIL
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/acme.sh
    volumes_from:
      - nginx-proxy
    networks:
      - nginx-proxy
    
networks:
  nginx-proxy:
    external: true
